default:
  http_metas:
    content-type: text/html

  metas:
    title:        ChoiqueCMS | Administración
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     es

  stylesheets:    [backend/main.css, backend/choique_settings.css]

  javascripts:    [jquery-1.4.2.min.js, no-conflict.js, /sfPrototypePlugin/js/prototype.js, /sfPrototypePlugin/js/effects.js,  /sfPrototypePlugin/js/controls.js, /sfPrototypePlugin/js/scriptaculous.js]

  has_layout:     on
  layout:         layout
