all:
  is_secure:        on

publish:
  is_secure:        on
  credentials:      [ [ reporter_admin, designer_admin ]]

unpublish:
  is_secure:        on
  credentials:      [ [ reporter_admin, designer_admin ]]

archive:
  is_secure:        on
  credentials:      [ [ reporter_admin, designer_admin ]]
