all:
  sf_guard_plugin:
    success_signin_url:   @homepage
    success_signout_url:  @homepage

  # Configuration parameters for RSS feed generation
  rss:
    feed:
      format:             atom1
      max_items:          20

  search_xml:
    shortname:            Buscar en choiqueCMS
    title:                Buscar en choiqueCMS

  sf_captchagd:
    image_width:          150 # image width in pixels
    routes_register:      false
    image_height:         70 # image height in pixels
    chars:                "123456789" # possible chars in captcha
    length:               4 # length of captcha
    font_size:            24 # font size
    # possible chars colors
    font_color:           ["252525", "8b8787", "550707", "3526E6", "88531E"]
    # chars fonts
    fonts:                ["akbar/akbar.ttf", "brushcut/BRUSHCUT.TTF", "molten/molten.ttf", "planet_benson/Planetbe.ttf", "whoobub/WHOOBUB_.TTF"]
    background_color:     DDDDDD # image background color
    border_color:         000000 # image border color

