<?php
// auto-generated by sfAdvancedAdmin
// date: 2011/08/31 10:41:09
?>

<ul class="sf_admin_actions">

<li><?php echo button_to(__('Cancel'), '@homepage', array (
  'class' => 'sf_admin_action_list',
)) ?></li>

   <li><?php echo submit_tag(__('Cambiar'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>

</ul>
