<?php
// auto-generated by sfAdvancedAdmin
// date: 2011/08/31 10:41:09
?>
<?php echo form_tag('sfGuardUser/changePassword', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'onsubmit'  => 'return true;'
)) ?>


<fieldset id="sf_fieldset_none" class="">


<div class="form-row">
  <?php echo label_for('sf_guard_user[password]', __($labels['sf_guard_user{password}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{password}')): ?>
    <?php echo form_error('sf_guard_user{password}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('password', array('type' => 'create')); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[new_password]', __($labels['sf_guard_user{new_password}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{new_password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{new_password}')): ?>
    <?php echo form_error('sf_guard_user{new_password}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('new_password', array('type' => 'create')); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[password_bis]', __($labels['sf_guard_user{password_bis}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{password_bis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{password_bis}')): ?>
    <?php echo form_error('sf_guard_user{password_bis}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('password_bis', array('type' => 'create')); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>

<?php include_partial('changepassword_actions', array()) ?>

</form>
