<?php
// auto-generated by sfAdvancedAdmin
// date: 2011/08/31 10:41:09
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'AdvancedAdmin') ?>

<?php use_stylesheet('backend/admin_theme_black') ?>

<div id="sf_admin_container">

<h1><?php echo __('Cambiar mi Contraseña', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('sfGuardUser/changepassword_header', array()) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('sfGuardUser/changepassword_messages', array( 'labels' => $labels)) ?>
<?php include_partial('sfGuardUser/changepassword_form', array('labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('sfGuardUser/changepassword_footer', array()) ?>
</div>

</div>
