<?php 
/*
 * Choique CMS - A Content Management System.
 * Copyright (C) 2012 CeSPI - UNLP <desarrollo@cespi.unlp.edu.ar>
 * 
 * This file is part of Choique CMS.
 * 
 * Choique CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License v2.0 as published by
 * the Free Software Foundation.
 * 
 * Choique CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Choique CMS.  If not, see <http://www.gnu.org/licenses/gpl-2.0.html>.
 */ ?>
<?php use_helper('Javascript') ?>

<!-- this was done in order not to redefine the autoAction generated by symfony for the section_id field -->
<?php if ($type!='filter'): ?>
  <?php echo input_hidden_tag('section[section_id]', $section->getSectionId()) ?>
  <?php echo input_auto_complete_tag('section_autocomplete_query',
                                     ($section->getSectionId()) ? $section->getParentSection()->getTitle() : null,
                                     'section/autocomplete?_csrf_token='.csrf_token() . (($section->isNew()) ? '' : '&section_id='.$section->getId()),
                                     array('size'      => 90, 
                                           'onBlur'    => "if ($('section_autocomplete_query').value.blank()) $('section_section_id').value = '';"),
                                     array('use_style' => true,
                                           'indicator' => 'search_indicator',
                                           'min_chars' => 3,
                                           'after_update_element' => "function (inputField, selectedItem) { $('section_section_id').value = selectedItem.id; $('clean_section_id').checked = false; if ($('section_section_id').value.blank()) $('section_autocomplete_query').value = ''; }")) ?>
  <?php echo checkbox_tag('clean_section_id',
                          true,
                          false,
                          array('onChange' => "if ($(this).checked) { $('section_section_id').value = ''; $('section_autocomplete_query').value =''; }")) ?>
  <?php echo __("Limpiar el campo") ?>                                           
<?php else: ?>
  <?php echo input_hidden_tag('filters[section_id]', 
                              isset($filters['section_id']) ? $filters['section_id'] : '') ?>
  <?php echo input_auto_complete_tag('section_autocomplete_query',
                                     (isset($filters['section_id']) && trim($filters['section_id']) != '') ? SectionPeer::retrieveByPK($filters['section_id'])->getTitle() : null,
                                     'section/autocomplete?for_filter=1&_csrf_token='.csrf_token(),
                                     array('size'      => 50, 
                                           'onBlur'    => "if ($('section_autocomplete_query').value.blank()) $('filters_section_id').value = '';"),
                                     array('use_style' => true,
                                           'indicator' => 'search_indicator',
                                           'min_chars' => 3,
                                           'after_update_element' => "function (inputField, selectedItem) { $('filters_section_id').value = selectedItem.id; $('clean_section_id').checked = false; if ($('filters_section_id').value.blank()) $('section_autocomplete_query').value = ''; }")) ?>
  <?php echo checkbox_tag('clean_section_id',
                          true,
                          false,
                          array('onChange' => "if ($(this).checked) { $('filters_section_id').value = ''; $('section_autocomplete_query').value =''; }")) ?>
  <?php echo __("Limpiar el campo") ?>
<?php endif ?>
<div id="search_indicator" style="display: none">
  <?php echo image_tag('common/indicator.gif') . ' ' . __('Buscando...') ?>
</div>
<div class="sf_admin_edit_help">
  <?php echo __("Comience a tipear el nombre de la sección y luego seleccionela de la lista desplegable") ?>
</div>