default:
  javascripts:
    - jquery-1.4.2.min.js
    - no-conflict.js
    - jquery-ui.min.js
    - /sfPrototypePlugin/js/prototype.js
    - /sfPrototypePlugin/js/scriptaculous.js
    - /sfPrototypePlugin/js/controls.js
    - json.js
    - layout.js